Repository GA-JOB/gajobBackEnd, pull requests merged in 2022-06, with the labels that each got.

#224 Response 데이터 추가 및 스크립 상태 여부 추가
  src/main/java/com/gajob/dto/posts/PostsScrapResponseDto.java
  src/main/java/com/gajob/dto/study/StudyReadDto.java
  src/main/java/com/gajob/dto/study/StudyScrapResponseDto.java
  src/main/java/com/gajob/entity/posts/PostsComments.java
  src/main/java/com/gajob/entity/study/Study.java
  src/main/java/com/gajob/service/posts/PostsServiceImpl.java
  src/main/java/com/gajob/service/study/StudyService.java
  src/main/java/com/gajob/service/study/StudyServiceImpl.java
Labels: ✨ Feature

#230 [#229] 임시 비밀번호 발송 메일 디자인 변경
  src/main/java/com/gajob/controller/findInfo/findInfoController.java
  src/main/java/com/gajob/service/findInfo/FindPasswordMailService.java
  src/main/java/com/gajob/service/findInfo/FindPasswordMailServiceImpl.java
Labels: ✨ Feature

#237 공모전 정보 낱개 조회 기능
  src/main/java/com/gajob/controller/crawling/ExhibitController.java
  src/main/java/com/gajob/service/crawling/ExhibitCrawling.java
  src/main/java/com/gajob/service/crawling/ExhibitCrawlingImpl.java
Labels: ✨ Feature

#239 [#238] 공모전 api 주소 이름 변경
  src/main/java/com/gajob/controller/crawling/ExhibitController.java
Labels: ✨ Feature

#240 [#200] 랭킹공모전 낱개 조회 기능
  src/main/java/com/gajob/controller/crawling/ExhibitRankingController.java
  src/main/java/com/gajob/service/crawling/ExhibitRankingCrawling.java
  src/main/java/com/gajob/service/crawling/ExhibitRankingCrawlingImpl.java
Labels: ✨ Feature

#246 [#244] 공모전 service 내 에러코드 변경
  src/main/java/com/gajob/service/crawling/ExhibitCrawlingImpl.java
  src/main/java/com/gajob/service/crawling/ExhibitRankingCrawlingImpl.java
Labels: ✨ Feature

#248 [#247] 채용정보를 영구저장할 기능 구현
  src/main/java/com/gajob/controller/openApi/JobFrameController.java
  src/main/java/com/gajob/dto/openApi/JobFrameDto.java
  src/main/java/com/gajob/dto/openApi/JobFrameResponseDto.java
  src/main/java/com/gajob/entity/openApi/JobFrame.java
  src/main/java/com/gajob/repository/openApi/JobFrameRepository.java
  src/main/java/com/gajob/service/openApi/JobFrameService.java
  src/main/java/com/gajob/service/openApi/JobFrameServiceImpl.java
Labels: ✨ Feature

#250 [#225] 비밀 댓글 여부 컬럼 추가
  src/main/java/com/gajob/dto/posts/PostsCommentsDto.java
  src/main/java/com/gajob/dto/posts/PostsCommentsResponseDto.java
  src/main/java/com/gajob/dto/study/StudyCommentsDto.java
  src/main/java/com/gajob/dto/study/StudyCommentsResponseDto.java
  src/main/java/com/gajob/entity/posts/PostsComments.java
  src/main/java/com/gajob/entity/study/StudyComments.java
  src/main/java/com/gajob/service/posts/PostsCommentsServiceImpl.java
  src/main/java/com/gajob/service/study/StudyCommentsServiceImpl.java
Labels: ✨ Feature

#251 [#249] 스크랩 목록 조회 시 에러 수정
  src/main/java/com/gajob/repository/posts/PostsScrapRepository.java
  src/main/java/com/gajob/repository/study/StudyScrapRepository.java
  src/main/java/com/gajob/service/posts/PostsScrapServiceImpl.java
  src/main/java/com/gajob/service/study/StudyScrapServiceImpl.java
Labels: 🐞 BugFix

#252 [#236] 스터디 모집 기능 구현
  src/main/java/com/gajob/controller/study/StudyRecruitmentController.java
  src/main/java/com/gajob/dto/study/StudyRecruitmentDto.java
  src/main/java/com/gajob/dto/study/StudyRecruitmentResponseDto.java
  src/main/java/com/gajob/entity/study/StudyRecruitment.java
  src/main/java/com/gajob/enumtype/ErrorCode.java
  src/main/java/com/gajob/enumtype/Result.java
  src/main/java/com/gajob/repository/study/StudyRecruitmentRepository.java
  src/main/java/com/gajob/service/study/StudyRecruitmentService.java
  src/main/java/com/gajob/service/study/StudyRecruitmentServiceImpl.java
Labels: ✨ Feature

#253 [#236] 스터디 모집 기능 구현
  src/main/java/com/gajob/service/study/StudyRecruitmentServiceImpl.java
Labels: ✨ Feature

#259 [#254] 채용정보 스크랩 기능 수정
  src/main/java/com/gajob/controller/openApi/JobScrapController.java
  src/main/java/com/gajob/dto/openApi/JobScrapResponseDto.java
  src/main/java/com/gajob/entity/openApi/JobScrap.java
  src/main/java/com/gajob/repository/openApi/JobScrapRepository.java
  src/main/java/com/gajob/service/openApi/JobScrapServiceImpl.java
Labels: ✨ Feature

#261 [#257] 공모전 정보 영구 저장소 구현
  src/main/java/com/gajob/controller/crawling/ExhibitFrameController.java
  src/main/java/com/gajob/dto/crawling/ExhibitFrameDto.java
  src/main/java/com/gajob/dto/crawling/ExhibitFrameResponseDto.java
  src/main/java/com/gajob/entity/crawling/ExhibitFrame.java
  src/main/java/com/gajob/repository/crawling/ExhibitFrameRepository.java
  src/main/java/com/gajob/service/crawling/ExhibitFrameService.java
  src/main/java/com/gajob/service/crawling/ExhibitFrameServiceImpl.java
Labels: ✨ Feature

#264 [#255] 공모전 스크랩 기능 수정
  src/main/java/com/gajob/controller/crawling/ExhibitScrapController.java
  src/main/java/com/gajob/dto/crawling/ExhibitScrapResponseDto.java
  src/main/java/com/gajob/entity/crawling/ExhibitScrap.java
  src/main/java/com/gajob/repository/crawling/ExhibitScrapRepository.java
  src/main/java/com/gajob/service/crawling/ExhibitScrapServiceImpl.java
Labels: ✨ Feature

#265 [#262] 공모전 관련 에러코드 수정
  src/main/java/com/gajob/service/crawling/ExhibitFrameServiceImpl.java
Labels: ✨ Feature

#266 [#260] 스터디 모집 지원자 수 추가
  src/main/java/com/gajob/dto/study/StudyReadDto.java
  src/main/java/com/gajob/entity/study/Study.java
Labels: ✨ Feature

#267 [#258] 랭킹공모전 정보 영구 저장소 구현
  src/main/java/com/gajob/controller/crawling/ExhibitRankingFrameController.java
  src/main/java/com/gajob/dto/crawling/ExhibitRankingFrameDto.java
  src/main/java/com/gajob/dto/crawling/ExhibitRankingFrameResponseDto.java
  src/main/java/com/gajob/entity/crawling/ExhibitRankingFrame.java
  src/main/java/com/gajob/repository/crawling/ExhibitRankingFrameRepository.java
  src/main/java/com/gajob/service/crawling/ExhibitRankingFrameService.java
  src/main/java/com/gajob/service/crawling/ExhibitRankingFrameServiceImpl.java
Labels: ✨ Feature

#268 [#256] 랭킹공모전 정보 스크랩 수정
  src/main/java/com/gajob/controller/crawling/ExhibitRankingScrapController.java
  src/main/java/com/gajob/dto/crawling/ExhibitRankingScrapResponseDto.java
  src/main/java/com/gajob/entity/crawling/ExhibitRankingScrap.java
  src/main/java/com/gajob/repository/crawling/ExhibitRankingScrapRepository.java
  src/main/java/com/gajob/service/crawling/ExhibitRankingScrapService.java
  src/main/java/com/gajob/service/crawling/ExhibitRankingScrapServiceImpl.java
Labels: ✨ Feature

#272 [#271] 채용공고 스크랩 정보 추가
  src/main/java/com/gajob/dto/openApi/JobScrapResponseDto.java
Labels: ✨ Feature

#275 간단한 에러 코드 처리 및 스터디 모집 기능 구현
  src/main/java/com/gajob/controller/study/StudyRecruitmentController.java
  src/main/java/com/gajob/dto/study/StudyRecruitmentResponseDto.java
  src/main/java/com/gajob/dto/study/StudyRecruitmentUpdateDto.java
  src/main/java/com/gajob/entity/study/StudyRecruitment.java
  src/main/java/com/gajob/enumtype/ErrorCode.java
  src/main/java/com/gajob/repository/user/UserRepository.java
  src/main/java/com/gajob/service/study/StudyRecruitmentService.java
  src/main/java/com/gajob/service/study/StudyRecruitmentServiceImpl.java
  src/main/java/com/gajob/service/user/UserService.java
Labels: ✨ Feature

#278 [#277] 학부, 유저 Response 데이터 추가
  src/main/java/com/gajob/dto/study/StudyRecruitmentResponseDto.java
  src/main/java/com/gajob/service/study/StudyRecruitmentServiceImpl.java
Labels: ✨ Feature

#280 [#279] 모집예정일 Status 추가
  src/main/java/com/gajob/enumtype/Status.java
  src/main/java/com/gajob/service/study/StudyRecruitmentServiceImpl.java
  src/main/java/com/gajob/service/study/StudyServiceImpl.java
Labels: ✨ Feature

#283 스터디 지원 취소 기능 추가
  src/main/java/com/gajob/controller/mypage/MyPageController.java
  src/main/java/com/gajob/controller/study/StudyRecruitmentController.java
  src/main/java/com/gajob/repository/study/StudyRecruitmentRepository.java
  src/main/java/com/gajob/service/mypage/MyPageService.java
  src/main/java/com/gajob/service/mypage/MyPageServiceImpl.java
  src/main/java/com/gajob/service/study/StudyRecruitmentService.java
  src/main/java/com/gajob/service/study/StudyRecruitmentServiceImpl.java
Labels: ✨ Feature

#286 [#285] 스터디 모집 결과 메일 전송 방식 변경
  src/main/java/com/gajob/service/study/StudyRecruitmentServiceImpl.java
Labels: ✨ Feature

#287 [#284] 공모전 스크랩 기능 수정
  src/main/java/com/gajob/controller/crawling/ExhibitScrapController.java
  src/main/java/com/gajob/dto/crawling/ExhibitScrapDto.java
  src/main/java/com/gajob/dto/crawling/ExhibitScrapResponseDto.java
  src/main/java/com/gajob/entity/crawling/ExhibitScrap.java
  src/main/java/com/gajob/repository/crawling/ExhibitScrapRepository.java
  src/main/java/com/gajob/service/crawling/ExhibitScrapService.java
  src/main/java/com/gajob/service/crawling/ExhibitScrapServiceImpl.java
Labels: ✨ Feature

#295 README.md UPDATE
  README.md
Labels: 📄 Docs

#296 README.md UPDATE
  README.md
Labels: 📄 Docs

#300 Study recruitment
  src/main/java/com/gajob/controller/study/StudyController.java
  src/main/java/com/gajob/dto/study/StudyReadDto.java
  src/main/java/com/gajob/service/study/StudyService.java
  src/main/java/com/gajob/service/study/StudyServiceImpl.java
Labels: 🐞 BugFix, ✨ Feature

#302 [#301] 스터디 지원 내역 조회 시 데이터 추가
  src/main/java/com/gajob/dto/study/StudyRecruitmentResponseDto.java
Labels: ✨ Feature

#304 [#303] SecurityConfig 파일 수정
  src/main/java/com/gajob/config/security/SecurityConfig.java
Labels: ✨ Feature
